---
header-includes:
  - \usepackage{physics}
  - |
    ```{=html}
    
    <script>
    window.MathJax = {
    loader: {load: ['[tex]/physics']},
    tex: {packages: {'[+]': ['physics']}}
    };
    
    let root = document.documentElement;
      document.addEventListener("scroll", evt => {
      root.style.setProperty("--scrolltop", root.scrollTop);
    });
    </script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-GKD85BYZJD"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-GKD85BYZJD');
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    ```
  - |
    ```{=latex}
    \usepackage{hyperref}
    \definecolor{00007f}{HTML}{00007f}
    ```
  
document-css: true
xnos-cleveref: true
xnos-capitalise: true
number-sections: true
xnos-warning-level: false
eqnos-number-by-section: true
reference-section-title: References
link-citations: true
link-bibliography: true
eqnos-eqref: true
eqnos-nameinlink: true
linkcolor: blue!50!black
urlcolor: blue!80!black
citecolor: blue!50!black
mainfont: Latin Modern

toc-title: Table of Contents
has-sidenote: false
root: home
---