---
header-includes:
  - \usepackage{physics}
  - |
    ```{=html}
    <script>
    window.MathJax = {
    loader: {load: ['[tex]/physics']},
    tex: {packages: {'[+]': ['physics']}}
    };
    
    </script>
    ```
  - |
    ```{=latex}
    \usepackage{hyperref}
    \definecolor{00007f}{HTML}{00007f}
    ```
  
document-css: true
xnos-cleveref: true
xnos-capitalise: true
number-sections: true
xnos-warning-level: false
eqnos-number-by-section: true
reference-section-title: References
link-citations: true
link-bibliography: true
eqnos-eqref: true
eqnos-nameinlink: true
linkcolor: blue!50!black
urlcolor: blue!80!black
citecolor: blue!50!black

toc-title: Table of Contents
---